// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziazjjmbgdurvyaoxfju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYXpqam1iZ2R1cnZ5YW94Zmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzU3ODIsImV4cCI6MjA3MjAxMTc4Mn0.y73e_UjBCJizuBELUg1QsaFl7ia5FReA3EvP0PLCMHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});